name: date-file
base: core20 
version: '1.0' 
summary: App to create files with the date in the filename # 79 char long summary
description: |
  A simple bash app, designed to create new files with the date in the file name in YYYY-mm-dd format

grade: stable # must be 'stable' to release into candidate/stable channels

confinement: strict # use 'strict' once you have the right plugs and slots

architectures: [ all ]

apps:
  date-file:
    command: bin/date-file.sh
    plugs:
      - touch
      - date

parts:
  date-file:
    plugin: dump
    source: .
    organize:
      date-file.sh: bin/date-file.sh