name: date-file
base: core20 
version: '0.1' 
summary: App to create files with the date in the filename # 79 char long summary
description: |
  A simple bash app, designed to create new files with the date in the file name in YYYY-mm-dd format

grade: devel # must be 'stable' to release into candidate/stable channels

confinement: devmode # use 'strict' once you have the right plugs and slots

architectures: [ all ]

apps:
  date-file:
    command: bin/date-file.sh

parts:
  date-file:
    plugin: dump
    source: .
    organize:
      date-file.sh: bin/date-file.sh